# Generated by Django 2.2 on 2021-02-05 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='A place where everyone has a great time!'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ninjas',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='dojo_ninja_app.Dojos'),
        ),
    ]
